### ISSUE TITLE
Merchant with wrong trades

### ISSUE THREAD

**Issue by Pacxxy** [TangoTek/TekTopia-Community#1037]
**Describe the bug**
When a merchant appears at my village, it trades me  emeralds for food, so I can't get tokens and play the mod. I haven't seen anyone having this bug, and I reinstalled the mod and downloaded it several times, and stil nothing.

![2019-11-10_16 05 37](https://user-images.githubusercontent.com/57578041/68546168-07617900-03d4-11ea-88dc-bbc724fd67a5.png)

**Comment by swccg** [comment]
Emeralds are not village specific, so the ones you trade for, mine naturally, or exploit by trading with cured zombie villagers are all interchangeable. Emeralds will never have green text.

That first merchant screenshot still looks like an issue, though. The merchant should be offering green food (for white emeralds), and you should have multiple trade options available (looks like the right arrow is disabled). Perhaps you didn't have your Town Hall active at the time?

**Comment by smmmadden** [comment]
it also looks like another resource pack and/or mod is also installed as the screenshots with the villagers are not Vanilla Villagers.  Could be a conflict there and/or incorrect Forge 1.12.2 build (e.g. 2768).

**Comment by Pacxxy** [comment]
I have the last forge version (2847), I don't have any other mods and I have a town hall, and I haven't spawned him, he spawned naturally and went to the town hall, like he have to do. And every time he only have one trade and is for food.

**Comment by smmmadden** [comment]
as stated in the wiki page, you should only be using build 2768.  Any other build has not been tested and are considered experimental builds so problems like these can come up.  Also make sure you aren't using a resource pack that will change appearances of the villagers (which seems to be the case in the screenshot).  It may not be the root cause, but you'll need to install the right build and make sure nothing is conflicting.  I use 2768 on a multiiplayer server and have not seen any issues like this.  https://sites.google.com/view/tektopia/home/about/installation

**Comment by Pacxxy** [comment]
So that's the problem. Thanks, and I don't use any resource pack
