### ISSUE TITLE
Villagers drop through platform and don't move anymore

### ISSUE THREAD

**Issue by iMelissaV** [TangoTek/TekTopia-Community#1038]
**Describe the bug**
I've been having the issue where my farmers drop trough my platform (even though it is not possible) in to the water and then they just stop moving, not even trying to make there way back to my island... Sometimes they even show the bed icon but don't move...
If this happens I move them using rails and a cart back to the main island and then they teleport so that they aren't stuck anymore...

**To Reproduce**
I don't know. It happens sometimes. 
I think it might be an issue between teleporting to warps or spawn on the server while villagers are working ... But still, I don't know.

**Screenshots**
![2019-11-21_16 15 58](https://user-images.githubusercontent.com/58040198/69350795-75325e00-0c7a-11ea-939c-64085bdd02ce.png)

** Server/Location **
Main Multiplay server: 192.99.232.93:25583
x: -2241, y: -311, z: 75

**Comment by iMelissaV** [comment]
![2019-11-21_16 15 58](https://user-images.githubusercontent.com/58040198/69350726-5b911680-0c7a-11ea-905c-6a4595125250.png)

**Comment by smmmadden** [comment]
Hi @iMelissaV - as a server owner myself and player of Tektopia since it was released, here are some pointers that will help you have better results.  Some of which have been reported by others or players on my servers also seen (including myself). :-)  First make sure you are running Forge 2768 - nothing lower or higher as they are not tested and have had issues.

**Water**
Tektopia Villagers do not interact with water well.  In fact, if you have a 1x1 square block of water and place a lilly pad on it (so you can step on it), some villagers will get stuck as they lose their pathing (direction where they need to go).  A gentle nudge/push off the lilly pad will send them to where they need to.
Farmers collecting sugar cane can also get confused and just stop moving in front of Sugar Cane that faces water because there is no direct path for them to go to.  To work around this, if you place water down and then Sugar Cane to be in front of it, cover the water (1 block on top) with a solid block or even Glass (I use Glass as it looks nicer to me). :-)  The villager will see that the path beyond the Sugar Cane is blocked so they will walk away from the Sugar Cane after collecting it.
The screen shot above shows a villager in a large body of unprotected water.  It should be surrounded by fencing/wall or something so that the villagers do not fall in or walk into the water - similar issue as above.

**Miners**
I've posted this for others previously, but for every Miner and Minecraft, plan to have a Druid available that can service/fill the shafts as Miners dig them.  If the mineshaft is open to all the way to the edge of the village, then you do not have enough Druids to help with the Mineshaft and/or Farms.  I now have 7 Mineshafts, 7 Miners and 8 Druids.  The extra Druids take care of my large Farm.
Mineshaft Tokens go disabled when they have reached a spot in the shaft they cannot continue past.  That could be due to the Village boundary, Lava, Water, or other unsafe area beyond the last block they did not break.  Make sure their full shafts can be mined completely.

**Villager Damage**
This is pretty common as well.  If the Town Hall Gem Token is turned (left or right) - not straight, it will stop the Necromancer from coming into the village and killing everything and anything that moves. :-)  He's pretty fierce so you need to make sure you have enough Guards that can help defeat him (with your help) and his minions.  Aside from the necromancer, if the lighting level is too low (7 or less), you will get unfriendly mobs spawning and they will attack villagers.  To get around this issue, I've installed Light Level Overlay Reloaded Mod that allows players to press F4 to see how much light there is nearby.  It's a valuable mod and I do recommend using it.

**Villager pausing with Beds over head**
If you do not have enough available beds for the villagers to sleep in, you will see this floating over their head and they simply stop moving until there is one.  Sometimes the beds they were in get unregistered (bug) due to either spawned children taking them over (2 people in 1 bed) and then what we do is break and re-place the bed.  Sometimes we need to do that PLUS remove the houses token and put it back on above the door.  Both methods seem to help but it does reoccur if you spawn a lot of children at once - just do one or two at a time.

This also means that you may be completely out of beds so you need to put up more houses with more beds and Chairs (very important - so they can rest/recoup) until the beds stay "YELLOW".  Yellow beds means there are not enough villagers to fill that bed.

I hope these tips help you playing the game as much as it does for us.  Good Luck! -Steve

**Comment by iMelissaV** [comment]
i understand that if they are i the water that they don't know the path, but my issue is that I don't understand how they get into the water I the first place... If they are in the water they are right beneath the platform... so they didn't fell from it... so what did happen? 

Could the issue be that there should be a full block underneath the farmland?

**Comment by rdster** [comment]
You need to have 2 levels for your floor...especially under farms.  Villagers can fall through a single layer if it is farmland...this has been an issue since beta.

Simply add another layer underneath, problem solved.

Also, Tango isn't going to hop on our server to check it out....this forum was supposed to be for Patreons only...playing on the Patreon server.

**Comment by MagmaSlime123** [comment]
Mod is dead. No updates since last year.
