### ISSUE TITLE
Enchanter has a buggy priority system

### ISSUE THREAD

**Issue by KeyokeDiacherus** [TangoTek/TekTopia-Community#328]
**Describe the bug**
If there is paper but not leather in the storeroom, the enchanter won't turn sugarcane into paper.
If there are books but not lapis in the storeroom, the enchanter won't turn paper/leather into books.

**To Reproduce**
1. Add sugarcane to the storeroom.
2. Enchanter turns the first batch into paper and drops it off.
3. Enchanter stands in the storeroom refusing to do anything.
4. Removing the paper from the chest allows the enchanter to keep working.
5. Similar behavior occurs with making books.

**Expected behavior**
The enchanter continues making paper until they have the opportunity to make books, and keeps making books until lapis is available.

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)? Main server 2
What are the world coordinates of your town hall marker? "Enchanter's Grotto"  -6039 10 -9530

**Additional context**
A workaround is to add a hopper below the storage chest that will suck up the paper/books as soon as he drops them off.

**Comment by TangoTek** [comment]
This is working as intended.  For crafters to not craft infinitely they need to know when to stop. Enchanters stop crafting paper when there is 12 paper in the storeroom.  They stop crafting books when there are 3 books in the storeroom.  This is necessary since some profession share an ingredient, like sugar cane with the chef.

There also isn't a big demand for books, which is why these numbers are low.  However, they might be a bit too low.  I'll double them.

**Comment by KeyokeDiacherus** [comment]
The problem with even just doubling it is that the merchant buys paper and
books, which means if you are attempting to sell them to the merchant you
have to constantly watch the storeroom and remove the handful of
paper/books he makes at a time.  Compare that to the chef's goods, which
get made until all their resources run out.  Perhaps at least increase the
cap up to the 1.25/1 stack of materials that the merchant will buy a day?

Thanks
