### ISSUE TITLE
Woodcutter not finishing job

### ISSUE THREAD

**Issue by luvzdeidara** [TangoTek/TekTopia-Community#46]
I've noticed that my woodcutter will chop out the bottom log, place a sapling but then won't finish chopping the tree down.

https://i.ibb.co/W5XQ2K5/2019-05-26-11-31-48.png
https://i.ibb.co/3MXSDwf/2019-05-26-11-32-25.png

**Comment by JohnyDL** [comment]
**Describe the bug**
Some Lumberjack jobs don't complete, leaving branches or whole trees

**To Reproduce**
watch a lumberjack team clearing a heavily wooded area naturally occurring area

**Expected behavior**
whole tree removed.

**Screenshots**
![2019-05-26_19 48 53](https://user-images.githubusercontent.com/5202568/58385915-bf9a9100-7fef-11e9-80d0-d685229a1499.png)

** Server/Location **
Offline and Survival 1 (Bugsy Towers)

**Comment by tomerorian** [comment]
I believe this is actually not an incomplete job, but a specific result of what I'm describing in here https://github.com/TangoTek/TekTopia-Community/issues/154#issuecomment-496760115

**Comment by TangoTek** [comment]
Duplicate. And should be fixed in 1.0.18.  Thank you!
