### ISSUE TITLE
Villagers Freezing

### ISSUE THREAD

**Issue by me2365** [TangoTek/TekTopia-Community#480]
Villagers dont work, sleep or do anything at all.

1: Villagers work, socialize sleep, etc
2: Wait for server to not have restarted recently

Villagers work, sleep, etc.

N/A

Survival #2 at around X=600 Z=150

I saw another report on this but it was already closed. This isn't just me either because other people I talk to in the server say it happens to them either for a short period of time or for a long period of time.

**Comment by LadyGwynn** [comment]
I think this is just an aspect of the problem reported in #461 and #478.

I have a village with just ten villagers: four farmers; two lumberjacks; one miner; one guard; one rancher; and one chef. I do not have a tavern.
From what I've noticed, about a third of my villagers will freeze in place wherever they are at any given sunset. A little way into the night, they will unfreeze and make their way to bed. I believe this coincides with when the villagers in their homes decide to stop socializing and go to bed.

My villagers have been getting progressively more and more unhappy, and I believe it is due to them missing out on their evening social time. This, in turn, is making it much less likely that I might have a heart spawn. I have yet to have a single heart in my village since I started it earlier this week. Also, due to my village size, I almost never get visiting nomads, making it nearly impossible to grow my village.
