### ISSUE TITLE
Kids Don't Go To School

### ISSUE THREAD

**Issue by me2365** [TangoTek/TekTopia-Community#490]
Any kid from my village and many other people's village's kids on the server don't go to school even if they have a valid school building and teacher. They still do loose happiness rapidly too for no reason. The teacher will sometimes stand in the school but eventually leaves after no one comes.

1: Have a valid school building and teacher
2: Have any amount of kids

They should be going to school everyday to increase intelligence

N/A

Server: Main Survival 2
Coordinates: X: 600 Z: 600

This can really effect your village as new workers start with 1 intelligence when they grow up since they never went to school.

**Comment by ialeed1** [comment]
To add to this more issues with school in version 1.0.43

- You can technically force kids to go to school by using a lead or pushing them to school but it will result in the child barely getting more than +1 int and no learning bubbles above their head. They will also bounce up and down glitching in the chair.
- Child Happiness will crash down to 0 during the day probably because going to school drops happiness but they never go to school and end up permanently at 0 happiness

**Comment by KeyokeDiacherus** [comment]
The kid in my village was also not being called to school.  I followed them around most of the day and they never got called to school.

**Comment by Makion65** [comment]
Having the same issue. I even unchecked all the other things for them to do, and they still just wander around the village.

**Comment by Shadows998** [comment]
Having the same issue on my end. Even with the newest feature to select the behaviors of the children, the issue persists
