### ISSUE TITLE
Villagers standing around

### ISSUE THREAD

**Issue by Makion65** [TangoTek/TekTopia-Community#493]
**Describe the bug**
My villagers seem to just stop what they are doing once the time of day reaches dusk. I thought that having a tavern might fix it, but I think my villagers are generally happy enough that "going to tavern" isn't important to them. 

They will stand around until the moon is at its peak, then they all head off to bed and go straight to sleep. Guards will patrol at the time they are supposed to, though. 

**To Reproduce**

**Expected behavior**

**Screenshots**

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)?
What are the world coordinates of your town hall marker?

**Additional context**

**Comment by paspinall42** [comment]
Same here, the tavern makes no difference, once it reaches dusk the villagers just stop what they are doing. This includes the Bard who I would have thought should go and play in the Tavern, and the cleric.

**Comment by KeyokeDiacherus** [comment]
I am also experiencing this issue (villagers stuck until midnight, no one using the tavern).  Even worse for me, several of them decide to go outside the village walls before doing this.

**Comment by Makion65** [comment]
Which villagers do you have going outside your town walls? I have farmers and lumberjacks mostly doing that.

**Comment by KeyokeDiacherus** [comment]
Good point, I should have clarified.  I'm getting random villagers (rancher, miner, lumberjack, etc.) going just outside the fence and standing there like zombie bait.

You're probably having those villagers (farmers, lumberjacks) go outside because they are looking for crops/trees outside the walls.  I'm in the middle of a desert, so I know that my lumberjack isn't looking for trees at least.

**Comment by Grurim2k** [comment]
I've had the same issue. I once had a farmer just take off for the hills, way outside of anything ever encountered by my other villagers, even beyond where my lumberjacks go. I never did figure out what he was doing, but he eventually was back in the village.

**Comment by Makion65** [comment]
![2019-06-22_18 32 35](https://user-images.githubusercontent.com/52094403/59969807-6bb29780-951c-11e9-8515-2a0a2f3b6b19.png)

This is about the time I'm seeing a large drop in villagers moving about.

**Comment by LadyGwynn** [comment]
Alright.. here we go again... 
This bug has been reported multiple times before, in #461, #478 and #480.

I have a small village with just over a dozen villagers.
From what I've noticed, about a third of my villagers will freeze in place wherever they are at any given sunset. A little way into the night, they will unfreeze and make their way to bed. I previously believed this coincided with when the villagers in their homes decide to stop socializing and go to bed, but since I installed my tavern token, many of them seem to stay frozen until midnight or later.
