### ISSUE TITLE
Butchers Not Working

### ISSUE THREAD

**Issue by me2365** [TangoTek/TekTopia-Community#510]
Butchers refuse to work when pens are overflowing with animals starving cause the ranchers can't keep up with so many animals. They kill animals sometimes but rarely, however they never kill cows. Some of my butchers have never killed a cow but they kill pigs and other things. I need leather for bookshelves for my enchanter but I can't make them without leather!

1: Have full animal pens and butcher
2: Butcher won't kill animals

That they kill animals that need to be killed when pens are overflowing. 

N/A

Survival 1 
X:600 Z: 600
 
And when they don't kill animals they just walk around the village doing nothing

**Comment by Turbo1234567896** [comment]
same

**Comment by JohnyDL** [comment]
Try using smaller pens, the size of the pen is what dictates how many animals will be in there and the butchers need to see it "full" before they take any animals out, If the pens are too big they never get "full" because the animals die of starvation before that "full" number is reached 

-> if Tango ever works on this I might suggest that he makes it so Butchers will go after animals with the lowest health first and maybe ignore the fullness check on animals under half hearts.
