### ISSUE TITLE
Contradictory Game Mechanic with Kids learning skills.

### ISSUE THREAD

**Issue by BILLSDORITOS** [TangoTek/TekTopia-Community#641]
Kids will learn skills from other villagers. (example: LVL 5 miner, lvl 2 bard, etc..)
   When they grow up to become nitwits, whatever profession you give them, the level of that profession is SET by their INT level. ( Example  LVL 40 INT = LVL 40 miner, and LVL 0 to everything else.)
   So if they discard everything they learn, in favor of their current INT why should this be a mechanic in the game?
   Instead of having it SET their prof.lvl, I think it should add instead.  

EXAMPLE:  INT (40) + Current PROF LVL (5) = 45.
  They should also keep other skills they learned from other villagers.
 
EX:  Miner (45), Bard (LVL 2), etc....

**Comment by SudsyMcGee** [comment]
I spotted this one too

**Comment by Snodderz** [comment]
Personally, I think the Intelligence level becoming skill level is overpowered. I agree that the skill level the child had should be added, instead of effectively overriden, but I think it should be added to half the intelligence level of the child. So maximum nitwit skill is going to be 50 + child skill levels

**Comment by Antirrhi** [comment]
I agree that adding skill & int would help make these mechanics compatible. To keep it from being overpowered, it could add a random number between 1 & the int (or some other range based on the int) to the skill, instead of the full int level.

**Comment by TangoTek** [comment]
Fixed in 1.0.59
