### ISSUE TITLE
Task suggestion: Drop off unusable items.

### ISSUE THREAD

**Issue by GrifterMage** [TangoTek/TekTopia-Community#65]
When a villager changes professions, they'll often have items in their inventory that their new profession doesn't use. Instead of those items rotting uselessly in their inventory or clearing them, maybe villagers could deliver any and all now-irrelevant items to storage, either as a one-time task when they change professions or as a low-priority task when they're already near the storage room.

**Comment by JohnyDL** [comment]
The deliver to storage AI could maybe then be simplified?

if item is needed for job
then return down to a limit
else return all

A similar system for miners would allow them to collect anything they come across while mining?

if a block is not {cobble, stone, stone variant, dirt. gravel bedrock, spawner} or (only applies to the listed items) if total block count in storage/all villager inventories %64 is not 0 and /64 is less than or equal to the number of partial stacks in storage
-then add the block or it's drop to inventory
-else void block/drop

This would allow miners to collect cobble, stone, stone variants, dirt. gravel and even loot/rails if they luckily run into a mine shaft for the player to use and how much they bring back is entirely controllable by the player ;)

**Comment by JohnyDL** [comment]
So I went through and found all the items relating to villager delivery failures causing perceived issues
#86 #87 #91 #101 #102 #137 #143 #149 #161 #171 #173 #180 #181 #199
I think most of them boil down to the delivery task being low and not getting completed regularly enough.
I was convinced my own enchanter was holding onto enchanted books, makes 4th and then it becomes a priority to return. I understand the logic in not returning one book at a time, but when these villagers visit the storage room and don't deposit things it's kind of irritating. Fundamentally I think all these reports stem from the same underlying issue and might be resolved by @GrifterMage's Solution of returning all items that villager doesn't need to the storage whenever they're in the storage room as an equally high priority to fetching more items to work with. (And maybe the blacksmith needs a randomiser for what it crafts based on its priorities the same way as the farmer got one for where they work)

**Comment by orangense** [comment]
For miners, since they spend so much time traveling to the storage room and back, is it possible to consolidate their trips to the surface? I have miners coming up for a bite to eat but they don't drop off resources, make a pickaxe, or make torches. It would be great if they could take a moment to see if there's anything else they'll need to finish their work day.

**Comment by JohnyDL** [comment]
I posted all my villager end of day inventory captures or 3 minecraft days (320 images) in #213 I haven't analysed it yet but I will be looking for trends that relate to here soon

**Comment by NerdyMindNYC** [comment]
Adding to the fold, my villagers are starting to get full inventories because they simply refuse to let anything go.  Oldest lumberjack is near full of saplings now and Enchanter has yet to deposit even 1 enchanted item other than books to storage.   Same with colored wools on the rancher and butcher.

![2019-06-01_07 34 52](https://user-images.githubusercontent.com/51106650/58748094-e7e81c80-8441-11e9-85b1-35f7011e54bf.png)
![2019-06-01_07 32 26](https://user-images.githubusercontent.com/51106650/58748095-ea4a7680-8441-11e9-9881-48a78318ca3c.png)
![2019-06-01_00 44 46](https://user-images.githubusercontent.com/51106650/58748097-ec143a00-8441-11e9-9d65-75ed157964d0.png)

**Comment by DocNox1408** [comment]
This is part of task #86 that should be connected to this task. The butcher will open the chest while holding wool but doesnt deposit it into the chest. Then when the rancher comes along to deliver wool they fight over the chest opening and closing it for several minutes until either its night and time to sleep or the rancher has just enough time to deposit thier wool. Is it possible that the butcher knows it has something it doesnt need put doesnt have the part to deposit that item if that makes sense.

**Comment by JohnyDL** [comment]
Something still seems broken in 1.0.37
![2019-06-15_12 57 54](https://user-images.githubusercontent.com/5202568/59551177-54e4d180-8f6d-11e9-9c06-451337e7a6e5.png)
