### ISSUE TITLE
bread production a bit light on

### ISSUE THREAD

**Issue by MetriCfan** [TangoTek/TekTopia-Community#690]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)?
What are the world coordinates of your town hall marker?

**Additional context**

**Comment by MetriCfan** [comment]
I have many chefs all with bread crafting on and lots of wheat but I never am able to get a surplus of bread in storage for trading.

**Comment by MetriCfan** [comment]
further to this we were getting some excess bread in the early days but now that meat is plentiful it's like they are neglecting breadmaking

**Comment by MetriCfan** [comment]
ok I turned off all baked potato production and the bread started to appear

**Comment by Snodderz** [comment]
If your meat supply is plentiful then isn't this just intended behavior? Meat is higher up in the AI/Priority list, so if you have uncooked meat in storage, that's what your chefs will do. This is why the AI GUI was added, so that you, as a player, could choose what you wanted to created. So if you want bread, turn off everything above bread in the AI GUI. Sounds like this is what you have done and it has worked. As potatoes are higher up in the AI List than Bread, this also tallies.

**Comment by MetriCfan** [comment]
yeah it is just something for the player to manage
