### ISSUE TITLE
Armour doesn't reduce damage taken

### ISSUE THREAD

**Issue by JohnyDL** [TangoTek/TekTopia-Community#70]
**Describe the bug**
Guard in full diamond armour took 3.0 damage from a zombie

**To Reproduce**
Guard with armour and no skill and then unleash a zombie

**Expected behavior**
damage reduced to maybe 1 or 0.5 hearts

** Server/Location **
Offline

**Additional context**
Zombie was spawned from a spawn egg not sure if that makes a difference

**Comment by JohnyDL** [comment]
![2019-05-27_03 02 14](https://user-images.githubusercontent.com/5202568/58391025-e37bc800-802b-11e9-9e0e-0c2f4560dd3c.png)

**Comment by HexFlareheart** [comment]
This actually appears to be a 'visual' bug, if that makes any sense. I've observed more directly, and it seems to be that the chat message is actually outputting the damage amount that the guard would take without armor; guards otherwise seem to be taking the correct amount of damage.

(On further inspection, the debug logs ALSO appear to be outputting the wrong damage amount as well.)

**Comment by TangoTek** [comment]
Good catch. Fixed to report actual damage taken now.  Thanks!
