### ISSUE TITLE
Farmers, chef stuck, flashing items (potatoes, porkchops) while standing still.

### ISSUE THREAD

**Issue by KeyokeDiacherus** [TangoTek/TekTopia-Community#76]
**Describe the bug**
Both our farmers and our chef are standing still.  Their hands briefly flash with items (potatoes, porkchops) as if they are trying to plant or cook them.  Breaking the kitchen sign, or the cropland, doesn't break them out of it.

**Expected behavior**
Their jobs normally.

** Server/Location **
Main(survival) - server 1
Town hall - Donkey-pichu

**Additional context**
Issue began after a crash and has persisted through another crash and a reset.

**Comment by binksayres** [comment]
Saw an issue like this when I first started my village.  My villagers would do nothing and just show items in their hands.  Turned out that the way I build my storage room broke the "Drop off items" portion.  I stacked two large chests one on top of the other with no air between them.  Removing the upper chest got them moving.

**Comment by TangoTek** [comment]
This was likely due to having chests in your storage room off the ground. (A bug now fixed).  Villagers would try to deliver items to those chests, then quickly realize they can't wait into floating air.
