### ISSUE TITLE
Miners dont Light when Building

### ISSUE THREAD

**Issue by Jamcdonald120** [TangoTek/TekTopia-Community#775]
When miners switch into fill mode instead of mine mode they no longer place torches for light.
![2019-07-24_23 33 04](https://user-images.githubusercontent.com/22623066/61846135-940b1a00-ae6b-11e9-8c67-b526e80f18b6.png)
![2019-07-24_23 33 13](https://user-images.githubusercontent.com/22623066/61846136-940b1a00-ae6b-11e9-86fd-f7b99c771d51.png)

**Comment by TangoTek** [comment]
From the looks of the picture they had an open ended cave exposed to sky which would mean the light level was always quite high where they were mining? Miners place down torches when the light level they are standing gets below 8.  So its not actually 'fill' mode that is causing this its the open ended tunnel. It was never dark so they never felt the need to put down a torch.

I moved the torch placing code into a more universal location so that miners will always attempt to place torches in mineshafts as they are inside it. This will include walking back and forth down the mineshaft.

**Comment by Jamcdonald120** [comment]
Oh, ok, that makes sense.  Does the change you made make miners start sprinkling torches everywhere they walk that is dark? or just registered mines?

**Comment by TangoTek** [comment]
hah, just in mines
