### ISSUE TITLE
Teachers use non-villager books

### ISSUE THREAD

**Issue by Snodderz** [TangoTek/TekTopia-Community#823]
**Describe the bug**
Teachers will use non-villager books to teach children. This means I'm already getting highly intelligent children before I have an enchanter to power the teacher. I can't really tell whether this is a difference in the intelligence gained from a villager book vs a non-villager book either.

**To Reproduce**
1. Have a teacher and 0 villager books
2. Put x6 non-villager books in storage
3. Watch your teacher teach with them
4. Check your childrens intelligence.

**Expected behavior**
Either:
1) - Non-Villager books can be used by teachers BUT have a massive nerf compared to villager books.
2) - Teachers will only use villager books

**Screenshots**

** Server/Location **
Single Player, Creative

**Additional context**
Version 1.0.78

**Comment by JohnyDL** [comment]
The enchanter doesn't really make enough books for the teacher(s) anyway and this is the only way to have enough books for high int chidren

**Comment by TangoTek** [comment]
Great feedback. Going with your option 1.

It makes me sad that it was just assumed that players had to make books for the teacher. I had no idea the enchanter wasn't making enough. I'll do my best to fix this.

**Comment by JohnyDL** [comment]
I think I asked for more books in the context of merchants, since it takes 8 to trade you really want 40+ on hand not 6-10 I've seen, (same for paper you ideally want 80 sat in storage) but so long as the player feeds a teacher books while they work teachers can use as many as 10 per day (and will without the player leave to fetch more and come back wasting student time during the day if you don't feed them books to use) just another one of my micromanaging tasks
