### ISSUE TITLE
Enchanter enchants books with no enchantments

### ISSUE THREAD

**Issue by UnholyFury92** [TangoTek/TekTopia-Community#825]
**Describe the bug**
Some but not all of the books that the enchanter enchants say enchanted book but have no enchantments

**To Reproduce**
Have 1.0.78
Have enchanter
Wait

**Expected behavior**
Make enchanted books with enchantments
**Screenshots**

** Server/Location **
SP

**Additional context**

**Comment by TangoTek** [comment]
Yea... this is technically possible since I'm using the vanilla enchantment generated.  The resulting enchant list can contain cursed enchantments.  I'm also removing all cursed enchantments from the list. So this means the list might end up empty if the original list was ONLY curses.

So... 
I just changed the code to attempt to generate an enchantment list up to 10 times. So if a list is all curses it'll just try again now. It should be extremely unlikely to get all curses 10 times in a row now.
