### ISSUE TITLE
Farmers ignoring farms

### ISSUE THREAD

**Issue by paspinall42** [TangoTek/TekTopia-Community#828]
**Describe the bug**

A series of 8 5x5 (less 1 for water) farms. the farmers only see 2 of them, they ignore all the other 6 even when their behaviour is set to only farm a crop in one of those 6, at that point they then wander off as though they have no job to do. 

**To Reproduce**
Build multiple small farms and observe. 

**Expected behavior**
I expect farmers to farm, based on a priority list for size/distance but also based on their ai. 

**Screenshots**
![image](https://user-images.githubusercontent.com/30393685/62013427-5ae3ea00-b18a-11e9-93e2-ab5ca24bd928.png)

The farmers only see the one by Sobertron and the once closest to myself (carrot and beat) even if set to wheat only they do not come and farm the wheat fields. 

** Server/Location **
Survival -2299 96 -7098

**Comment by TangoTek** [comment]
[https://i.gyazo.com/316a560ecc78aa2d17b96532c03b15b3.png](url)
I went there and the first day the farmers were farming both wheat plots.

However...
Your village is a bit unusual in its verticality.  Farms near the town hall have a better chance of being scanned than farms far away from the TH. This applies both horizontally and vertically and its just an optimization to look for farms where they are more likely to be.  The farther a farm is away from TH (horizontally or vertically) the longer it will likely take to be found.  Its all just random number sampling.

So I suspect that your lower farms are not being detected very quickly (possibly many minutes after the village is registered).  If I increase the range of block scanning more it'll slow the detection down of all farms.  Unless of course I increase the sample rate, but that will start to add performance issues.

So I'm not sure.  I'm open to suggestions.

**Comment by JohnyDL** [comment]
Does the pathfinding system know if the block is a dirt variant?

If block added to pathfinding is dirt/grass/mycelium/podzel note where it is
insertion to list based on radius (one before the first that's larger than it)
scan only these blocks for if they're farmland (no point checking air or stone or leaves)
scanning 0, 1, 3, 6, 10, 15, 21... n(n+1)/2 moving them to the end of the list after scanning
once n(n+1)/2 is larger than the length of the list start at 0 again without sorting
remove the block from this list when it is checked and turns out to be not dirt variant or no-longer supporting a pathable space

Each pass will look at about root length potential farm spots
it will scan the earlier entries on the list sooner than later ones
it will rescan the same block less often early on and so hit more potential spots
it will rescan the oldest previously scanned more as time goes on
it won't waste time on things that can't be made into farm squares
the list as a whole eventually becomes pseudo random after a lot of passes but it still retains the rescanning the least recently scanned blocks sooner than less recently scanned ones on average
And Maybe resort the list whenever the area is loaded to allow some control by the player (adding or removing even a small number of blocks shakes-up which ones are checked in which order after a handful of passes)

Assuming you can scan 10 blocks per tick that's 100 per second, there are 160,000 grass blocks (at the start of the village that seems reasonable it'd take 4 seconds per pass) and farms of 24 tiles should be found in about 67 seconds on average, the village would take 1600 seconds to scan every block once on average that's 26 minutes a little over a day-night cycle

This idea might be a case of CPU time vs RAM space and might not be at all feasible, 160,000 offsets for a village (x,y,z <400 means 6 bytes each) is almost an extra 1MB, and might be fine for single player but not for servers with multiple villages, and if you're only scanning 1 block per tick not 10 blocks per tick this makes my napkin math much less useful.

**Comment by paspinall42** [comment]
Yes many minutes but the village was loaded for days and they didn't touch the wheat, the wheat farmers were instead wandering around outside the mine on totally the opposite side of the village doing nothing.

**Comment by JohnyDL** [comment]
This may sound ridiculously simple compared to the last idea but why not scan under player? maybe every 20th tick even? all the player has to do to make sure something is scanned is stand on top of the relevant block? while the normal scanning is going on the other 95% of the time
