### ISSUE TITLE
Villager Inventory - Keeping Non-Villager items after Villager items available

### ISSUE THREAD

**Issue by Takaarakat** [TangoTek/TekTopia-Community#848]
I have been noticing that most of our villagers are still holding onto non villager items even tho they have villager items in their inventory or available from the storage room.  I'm not sure if it's a bug that they're not using them or putting them back in storage.  But if it's not a bug, I have a suggestion that once the same material is available as a villager item, that they empty their inventory of the non villager item.  I think that this might help stop the villagers from making non-villager items when they have all the means and ability to make villager items and it will also help us as a player to make sure that we can clear all non villager items out of the storage.

**Comment by stickrai** [comment]
Such a big yes on this. love getting normal cake's because somehow he decided to use a normal bucket for milk even though everything else was a villager item

**Comment by TangoTek** [comment]
I honestly think this is just a response to the cake/bucket bug which was just fixed.  Now that it won't happen any more you shouldn't have any non-villager items in your storage unless you put them there?

I say this mostly because doing what you ask is a very big change that would likely end up causing a few more bugs. So I'm not going to tackle it now. Sorry.

**Comment by Takaarakat** [comment]
I think you are right! I just checked a few villagers and most of what I saw is gone now. whether they used it or not, but it's a win in my book cause it's all villager out put now!  Thanks Tango!
