### ISSUE TITLE
Guard Armor Options Buggy?

### ISSUE THREAD

**Issue by Takaarakat** [TangoTek/TekTopia-Community#886]
I'm trying to get my guards to only wear enchanted armor.  

When I uncheck the diamond and iron non enchanted armor options and only leave the enchanted armor checked, they won't wear anything. 

 If I check just diamond armor and enchanted armor, they end up choosing some unenchanted gear over enchanted gear.

I see you wrote that "Guards now consider enchantments when choosing armor and weapons" for the Version 1.0.87 updates.  Is that just meaning that they'll look at it and possibly decide they don't want it? or are they supposed to choose any enchantments over none?

**Comment by TangoTek** [comment]
"When I uncheck the diamond and iron non enchanted armor options and only leave the enchanted armor checked, they won't wear anything."
This is correct.

"If I check just diamond armor and enchanted armor, they end up choosing some unenchanted gear over enchanted gear."  
You have to specify what they chose over the enchanted gear.  It would make sense to choose diamond unenchanted over iron that is only slightly enchanted.  It evaluates the overall defensive properties of any armor and equips the best.

As far as the "Wear Enchanted Armor" option. Think of that like "Should I ALSO consider wearing enchanted armor?"  Because if you have all material types turned off, that means wear nothing.

**Comment by Takaarakat** [comment]
Okay! It does make sense, I just wasn't sure. Thank you for the quick reply! I know you're busy!! :D
