### ISSUE TITLE
bug: villagers suiciding

### ISSUE THREAD

**Issue by stickrai** [TangoTek/TekTopia-Community#890]
There's plenty of food, they just chose not to eat but instead finish their task. 
... until they die.
https://gyazo.com/1810975a9094ba4e2e27ce195c2ec07d
https://gyazo.com/1c15ccf423fc86fbb2739f1cbe5efc32

Edit;
did a bit more research.
Apparently i was close enough to the village to trigger health and stuff to go down, but nto close enough for them to go to bed during night time.
TPed to /home and they continued as usual. but it was already too late.

https://gyazo.com/18563232ae3f11c8fb61938a8003a600

**Comment by TangoTek** [comment]
I changed it so that villagers won't lose hunger if the storage room isn't loaded.  I suspect you were in a situation where the town hall was loaded (and therefore had a valid village) but your storage room wasn't in range to be loaded.  The villagers on that side of the village kept working but couldn't get food since the storage wasn't loaded.
