### ISSUE TITLE
[Suggestion] change the word "collect" for "replant" in the Lumberjacks GUI

### ISSUE THREAD

**Issue by ghost** [TangoTek/TekTopia-Community#933]
I found a closed suggestion: Turn off sapling replanting #905
Where JohnyDL commented: "You can do that by turning off sapling collection, if they can't collect the saplings they can't replant them"
Like JenesisDark I also thought of sapling collection more like a farming tool.

Lumberjaks alway collect saplings but replant it or not. So i suggest to change the word "collect" for "replant" in the Lumberjacks GUI. Is more explicit and easy to understand.

**Comment by TangoTek** [comment]
Collecting (as it is now) just means should they pick up saplings on the ground.
Replanting means should they plant a new tree after chopping one down.
They aren't really related at all. Johny's advice doesn't really make sense since a Lumberjack could have up to 60 saplings of each type in his inventory already.
